#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------
# Paths: allow execution from scripts/
# ------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# Enable recursive globbing (**)
shopt -s globstar nullglob

RULES=(**/rules/*.yml)
if [ ${#RULES[@]} -eq 0 ]; then
  echo "[!] No Sigma rules found under **/rules/*.yml"
  exit 1
fi

# ------------------------------------------------------------
# Output dir inside scripts/
# ------------------------------------------------------------
OUTROOT="$SCRIPT_DIR/conversions"
SHOW=0
usage() {
  cat <<EOF
Usage: ./convert_all_rules.sh [--show]

  --show   Print a short summary at the end (paths + counts)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --show) SHOW=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[!] Unknown argument: $1"; usage; exit 1 ;;
  esac
done

mkdir -p "$OUTROOT"

# ------------------------------------------------------------
# Validate
# ------------------------------------------------------------
echo "[*] Sigma syntax validation"
sigma check "${RULES[@]}"

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
safe_name() {
  # Convert a rule path to a safe filename
  # e.g. CVE-2025-xxxx/rules/my_rule.yml -> CVE-2025-xxxx__my_rule.yml
  echo "$1" | sed 's#^\./##; s#/#__#g'
}

to_one_line() {
  # Collapse newlines -> spaces, trim, normalize spaces
  # Useful for query_string engines that require a single line.
  sed ':a;N;$!ba;s/\r//g;s/\n/ /g' | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//'
}

write_index() {
  local idx="$OUTROOT/README_CONVERSIONS.md"
  cat > "$idx" <<'MD'
# Sigma conversions — SOC usage guide

This folder is generated by `scripts/convert_all_rules.sh`.

## Structure

```
conversions/<label>/raw/       <- exact sigma output (use this by default)
conversions/<label>/one-line/  <- single-line variant (only if your SIEM requires it)
```

## Folders and target SIEMs

| Folder | SIEM / product | Query language | Pipeline | Requires |
| :--- | :--- | :--- | :--- | :--- |
| `OpenSearch_ECS/` | OpenSearch, Wazuh | Lucene | sysmon (ECS) | sigma 3.x |
| `Lucene_Sysmon/` | Elasticsearch | Lucene | sysmon (ECS) | sigma 3.x |
| `Elastic_EQL/` | Elastic Security | EQL | sysmon | sigma 3.x |
| `Elastic_ESQL/` | Elastic Security 8.11+ | ES\|QL | sysmon | sigma 3.x |
| `Elastic_ElastAlert/` | ElastAlert 2 | Lucene | windows-logsources | sigma 3.x |
| `Splunk_Windows/` | Splunk Enterprise Security | SPL | splunk_windows | sigma 3.x |
| `Splunk_SPL2/` | Splunk ES 7+ / SPL2 | SPL2 | splunk_windows | sigma 3.x |
| `RSA_NetWitness/` | RSA NetWitness | NetWitness | sysmon | plugin netwitness |
| `Microsoft_Sentinel_KQL/` | Microsoft Sentinel | KQL (Kusto) | sentinel_asim | plugin kusto |
| `Microsoft_Defender_XDR_KQL/` | Microsoft Defender XDR | KQL (Kusto) | microsoft_xdr | plugin kusto |
| `Azure_Monitor_KQL/` | Azure Monitor / Log Analytics | KQL (Kusto) | azure_monitor | plugin kusto |
| `QRadar_AQL/` | IBM QRadar | AQL | none | sigma 2.x + plugin qradar |

## Important notes

- Use `raw/` by default. Use `one-line/` only if your platform requires a single-line query string.
- Terminal wrapping in your shell is not real newlines — always copy from the generated files.
- For kusto targets: web/network rules fall back to --without-pipeline when the pipeline has no
  mapping for web fields (e.g. cs-uri-stem). The query is still valid KQL with raw field names.
- RSA NetWitness, kusto and QRadar folders are generated only if the respective plugins are installed.
- QRadar native AQL requires sigma-cli 2.x. Under sigma-cli 3.x the qradar plugin is Compatible=no
  and this folder is not generated. Use convert_to_qradar.sh for a Lucene fallback instead.
MD
}

target_available() {
  sigma list targets 2>/dev/null | grep -qw "$1"
}

convert_per_rule() {
  local label="$1"
  local target="$2"
  local pipeline="$3"           # pipeline to apply; empty = no pipeline
  local oneline_mode="$4"
  local scope="${5:-windows}"   # 'windows' = Windows rules only; 'all' = every rule
  local fallback="${6:-no}"     # 'yes' = retry with --without-pipeline if pipeline fails

  local base="$OUTROOT/$label"
  mkdir -p "$base/raw" "$base/one-line"

  echo "[*] $label"

  local count=0
  local fallback_count=0
  local skipped=0
  for r in "${RULES[@]}"; do
    local fname
    fname="$(safe_name "$r")"
    local out_raw="$base/raw/${fname%.yml}.txt"
    local out_one="$base/one-line/${fname%.yml}.txt"

    # Apply pipeline according to scope:
    #   'all'     -> always apply (e.g. sentinel_asim maps every logsource to ASIM tables)
    #   'windows' -> only for Windows rules, skip Linux/web/network to avoid wrong field mapping
    local pipeline_args=()
    if [[ -n "$pipeline" ]]; then
      if [[ "$scope" == "all" ]] || grep -qE "^\s+product: windows" "$r"; then
        pipeline_args=("-p" "$pipeline")
      fi
    fi

    local stderr_tmp
    stderr_tmp="$(mktemp)"
    sigma convert -t "$target" "${pipeline_args[@]}" "$r" \
      > "$out_raw" 2>"$stderr_tmp" || true

    if [[ -s "$out_raw" ]]; then
      rm -f "$stderr_tmp"
      count=$((count+1))
    elif [[ "$fallback" == "yes" ]] && [[ ${#pipeline_args[@]} -gt 0 ]]; then
      # Pipeline failed for this rule; retry without pipeline (raw field names)
      rm -f "$stderr_tmp"
      stderr_tmp="$(mktemp)"
      sigma convert -t "$target" --without-pipeline "$r" \
        > "$out_raw" 2>"$stderr_tmp" || true
      if [[ -s "$out_raw" ]]; then
        rm -f "$stderr_tmp"
        fallback_count=$((fallback_count+1))
      else
        cat "$stderr_tmp" >> "$out_raw"
        rm -f "$stderr_tmp"
        echo "    [skip] $(basename "$r")"
        skipped=$((skipped+1))
      fi
    else
      cat "$stderr_tmp" >> "$out_raw"
      rm -f "$stderr_tmp"
      echo "    [skip] $(basename "$r")"
      skipped=$((skipped+1))
    fi

    if [[ -s "$out_raw" ]]; then
      if [ "$oneline_mode" = "yes" ]; then
        to_one_line < "$out_raw" > "$out_one"
      else
        cp -f "$out_raw" "$out_one"
      fi
    fi
  done

  local summary="$count rules converted"
  [[ $fallback_count -gt 0 ]] && summary+="  $fallback_count via --without-pipeline fallback"
  [[ $skipped -gt 0 ]]        && summary+="  $skipped skipped"
  echo "    $summary  -> $base/raw/"
}

# ------------------------------------------------------------
# Build conversions index guide
# ------------------------------------------------------------
write_index

# ------------------------------------------------------------
# Targets
# NOTE:
# - "one-line = yes" ONLY where your SIEM needs a query_string single-line.
# - For others, keep raw formatting (safer).
# - scope "all"     = apply pipeline to every rule (required for backends that need a pipeline)
# - scope "windows" = apply pipeline to Windows rules only (optional-pipeline backends)
# - fallback "yes"  = retry with --without-pipeline when pipeline has no mapping for a logsource
# ------------------------------------------------------------

# --- Elasticsearch / OpenSearch ---
convert_per_rule "OpenSearch_ECS"     "opensearch_lucene"   "sysmon"             "yes" "all"
convert_per_rule "Lucene_Sysmon"      "lucene"              "sysmon"             "yes" "all"
convert_per_rule "Elastic_EQL"        "eql"                 "sysmon"             "no"  "all"
convert_per_rule "Elastic_ESQL"       "esql"                "sysmon"             "no"  "all"
convert_per_rule "Elastic_ElastAlert" "elastalert"          "windows-logsources" "no"  "all"

# --- Splunk ---
convert_per_rule "Splunk_Windows"     "splunk"              "splunk_windows"     "no"  "all"
convert_per_rule "Splunk_SPL2"        "splunk_spl2"         "splunk_windows"     "no"  "all"

# --- RSA NetWitness (optional plugin) ---
if target_available "net_witness"; then
  convert_per_rule "RSA_NetWitness" "net_witness" "sysmon" "no" "windows"
else
  echo "[!] Target 'net_witness' not available — skipping RSA NetWitness"
  echo "    To enable: sigma plugin install netwitness"
fi

# --- Microsoft (Kusto / KQL) — optional plugin ---
if target_available "kusto"; then
  # Microsoft Sentinel (ASIM tables — broadest coverage across all logsources)
  convert_per_rule "Microsoft_Sentinel_KQL"      "kusto" "sentinel_asim"    "no" "all"     "yes"
  # Microsoft Defender XDR (Windows endpoint tables: DeviceProcessEvents, etc.)
  convert_per_rule "Microsoft_Defender_XDR_KQL"  "kusto" "microsoft_xdr"    "no" "windows" "yes"
  # Azure Monitor / Log Analytics (generic; covers Windows, Linux and cloud sources)
  convert_per_rule "Azure_Monitor_KQL"           "kusto" "azure_monitor"    "no" "all"     "yes"
else
  echo "[!] Target 'kusto' not available — skipping Microsoft KQL targets"
  echo "    To enable: sigma plugin install kusto"
fi

# --- QRadar AQL (sigma 2.x only — Compatible=no in sigma 3.x) ---
# target_available returns false under sigma 3.x so this block is naturally skipped.
# Under sigma 2.x with the qradar plugin installed it runs transparently.
if target_available "qradar"; then
  convert_per_rule "QRadar_AQL" "qradar" "" "no" "all"
elif target_available "ibm-qradar-aql"; then
  convert_per_rule "QRadar_AQL" "ibm-qradar-aql" "" "no" "all"
else
  echo "[!] Target 'qradar' not available — skipping QRadar native AQL"
  echo "    Under sigma-cli 3.x both qradar plugins are Compatible=no"
  echo "    To enable: use sigma-cli 2.x + sigma plugin install qradar"
  echo "    Lucene fallback: bash scripts/convert_to_qradar.sh"
fi

echo
echo "[+] Validation + conversions completed."
echo "[+] Output directory: $OUTROOT"
echo "[+] Guide: $OUTROOT/README_CONVERSIONS.md"

if [ "$SHOW" -eq 1 ]; then
  echo
  echo "[i] Targets generated:"
  find "$OUTROOT" -maxdepth 2 -type d -name raw -print | sed 's#^# - #'
fi
