#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------
# Paths: allow execution from scripts/
# ------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# Enable recursive globbing (**)
shopt -s globstar nullglob

RULES=(**/rules/*.yml)
if [ ${#RULES[@]} -eq 0 ]; then
  echo "[!] No Sigma rules found under **/rules/*.yml"
  exit 1
fi

# ------------------------------------------------------------
# Output dir inside scripts/
# ------------------------------------------------------------
OUTROOT="$SCRIPT_DIR/conversions"
SHOW=0
usage() {
  cat <<EOF
Usage: ./convert_all_rules.sh [--show]

  --show   Print a short summary at the end (paths + counts)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --show) SHOW=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[!] Unknown argument: $1"; usage; exit 1 ;;
  esac
done

mkdir -p "$OUTROOT"

# ------------------------------------------------------------
# Validate
# ------------------------------------------------------------
echo "[*] Sigma syntax validation"
sigma check "${RULES[@]}"

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
safe_name() {
  # Convert a rule path to a safe filename
  # e.g. CVE-2025-xxxx/rules/my_rule.yml -> CVE-2025-xxxx__my_rule.yml
  echo "$1" | sed 's#^\./##; s#/#__#g'
}

to_one_line() {
  # Collapse newlines -> spaces, trim, normalize spaces
  # Useful for query_string engines that require a single line.
  sed ':a;N;$!ba;s/\r//g;s/\n/ /g' | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//'
}

write_index() {
  local idx="$OUTROOT/README_CONVERSIONS.md"
  cat > "$idx" <<'MD'
# 🧾 Sigma Conversions – SOC Copy/Paste Guide

This folder is generated by `scripts/convert_all_rules.sh`.

## 📁 Structure
- `conversions/<SIEM>/raw/`      → exact output from Sigma (recommended default)
- `conversions/<SIEM>/one-line/` → single-line variant (ONLY when your SIEM requires it)

## ✅ Where to copy/paste

### 🟦 OpenSearch / Lucene (ECS / Sysmon)
- Use: `OpenSearch_ECS/raw/*.txt`
- If your platform requires ONE LINE (ex: query_string): use `OpenSearch_ECS/one-line/*.txt`

### 🟨 Splunk (Windows)
- Use: `Splunk_Windows/raw/*.txt`
- Paste into: Splunk Search / Correlation Search query field (depending on your app)

### 🟥 Elastic / ElastAlert (legacy)
- Use: `Elastic_ElastAlert/raw/*.txt`
- Paste into: ElastAlert rule file (YAML) / query field (depending on the output)

### 🟪 Elastic EQL
- Use: `Elastic_EQL/raw/*.txt`
- Paste into: EQL rule query field

### 🟫 RSA NetWitness
- Use: `RSA_NetWitness/raw/*.txt`
- Paste into: NetWitness query / rule content area

### 🟩 Sentinel (Sysmon)
- Use: `Sentinel_Sysmon/raw/*.txt`
- Paste into: Microsoft Sentinel analytics rule (KQL / query field depending on backend)

## ⚠️ Important note about “line breaks”
- Terminal wrapping ≠ real newlines.
- Always copy from the **generated files** to preserve correctness.
MD
}

convert_per_rule() {
  local label="$1"
  local target="$2"
  local pipeline="$3"
  local oneline_mode="$4"  # yes/no

  local base="$OUTROOT/$label"
  mkdir -p "$base/raw" "$base/one-line"

  echo "[*] 🔁 $label"

  local count=0
  for r in "${RULES[@]}"; do
    local fname
    fname="$(safe_name "$r")"
    local out_raw="$base/raw/${fname%.yml}.txt"
    local out_one="$base/one-line/${fname%.yml}.txt"

    # Convert ONE rule at a time => clean separation, no mixing
    sigma convert -t "$target" -p "$pipeline" "$r" > "$out_raw"

    # Generate one-line variant only when requested
    if [ "$oneline_mode" = "yes" ]; then
      cat "$out_raw" | to_one_line > "$out_one"
    else
      # Keep identical copy to avoid confusion; analyst can ignore one-line dir
      cp -f "$out_raw" "$out_one"
    fi

    count=$((count+1))
  done

  echo "    ✅ $count rules → $base/raw/ (and one-line/)"
}

# ------------------------------------------------------------
# Build conversions index guide
# ------------------------------------------------------------
write_index

# ------------------------------------------------------------
# Targets
# NOTE:
# - "one-line = yes" ONLY where your SIEM needs a query_string single-line.
# - For others, keep raw formatting (safer).
# ------------------------------------------------------------
convert_per_rule "OpenSearch_ECS"      "opensearch_lucene" "sysmon"           "yes"
convert_per_rule "Lucene_Sysmon"       "lucene"            "sysmon"           "yes"
convert_per_rule "Splunk_Windows"      "splunk"            "splunk_windows"   "no"
convert_per_rule "Elastic_ElastAlert"  "elastalert"        "windows-logsources" "no"
convert_per_rule "Elastic_EQL"         "eql"               "sysmon"           "no"
convert_per_rule "RSA_NetWitness"      "net_witness"       "sysmon"           "no"
convert_per_rule "Microsoft_Sentinel_KQL" "kusto" "sysmon" "no"

echo
echo "[+] ✅ Validation + conversions completed."
echo "[+] 📁 Output directory: $OUTROOT"
echo "[+] 📄 Guide: $OUTROOT/README_CONVERSIONS.md"

if [ "$SHOW" -eq 1 ]; then
  echo
  echo "[i] Targets generated:"
  find "$OUTROOT" -maxdepth 2 -type d -name raw -print | sed 's#^# - #'
fi

